"""add soft delete and audit hardening fields

Revision ID: 560552e09e06
Revises: 
Create Date: 2026-05-07 22:00:03.634168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560552e09e06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('actor_email', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('metadata_json', sa.Text(), nullable=True))
    op.add_column('activities', sa.Column('ip_address', sa.String(), nullable=True))
    op.alter_column('activities', 'workspace_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('customers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'users', ['deleted_by_user_id'], ['id'])
    op.add_column('delivery_services', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('delivery_services', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_services', sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'delivery_services', 'users', ['deleted_by_user_id'], ['id'])
    op.add_column('file_assets', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('file_assets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('file_assets', sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'file_assets', 'users', ['deleted_by_user_id'], ['id'])
    op.add_column('finance_entries', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('finance_entries', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('finance_entries', sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'finance_entries', 'users', ['deleted_by_user_id'], ['id'])
    op.add_column('inventory_items', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('inventory_items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inventory_items', sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_items', 'users', ['deleted_by_user_id'], ['id'])
    op.add_column('jobs', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['deleted_by_user_id'], ['id'])
    op.add_column('offers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('offers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('offers', sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offers', 'users', ['deleted_by_user_id'], ['id'])
    op.add_column('request_tickets', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('request_tickets', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('request_tickets', sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request_tickets', 'users', ['deleted_by_user_id'], ['id'])
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['deleted_by_user_id'], ['id'])
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    op.add_column('workspace_members', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workspaces', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('status', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('primary_contact_name', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('primary_contact_email', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('primary_contact_phone', sa.String(), nullable=True))
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_column('workspaces', 'primary_contact_phone')
    op.drop_column('workspaces', 'primary_contact_email')
    op.drop_column('workspaces', 'primary_contact_name')
    op.drop_column('workspaces', 'logo_url')
    op.drop_column('workspaces', 'status')
    op.drop_column('workspaces', 'slug')
    op.drop_column('workspace_members', 'updated_at')
    op.drop_column('users', 'is_super_admin')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'deleted_by_user_id')
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('tasks', 'is_deleted')
    op.drop_constraint(None, 'request_tickets', type_='foreignkey')
    op.drop_column('request_tickets', 'deleted_by_user_id')
    op.drop_column('request_tickets', 'deleted_at')
    op.drop_column('request_tickets', 'is_deleted')
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_column('offers', 'deleted_by_user_id')
    op.drop_column('offers', 'deleted_at')
    op.drop_column('offers', 'is_deleted')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'deleted_by_user_id')
    op.drop_column('jobs', 'deleted_at')
    op.drop_column('jobs', 'is_deleted')
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.drop_column('inventory_items', 'deleted_by_user_id')
    op.drop_column('inventory_items', 'deleted_at')
    op.drop_column('inventory_items', 'is_deleted')
    op.drop_constraint(None, 'finance_entries', type_='foreignkey')
    op.drop_column('finance_entries', 'deleted_by_user_id')
    op.drop_column('finance_entries', 'deleted_at')
    op.drop_column('finance_entries', 'is_deleted')
    op.drop_constraint(None, 'file_assets', type_='foreignkey')
    op.drop_column('file_assets', 'deleted_by_user_id')
    op.drop_column('file_assets', 'deleted_at')
    op.drop_column('file_assets', 'is_deleted')
    op.drop_constraint(None, 'delivery_services', type_='foreignkey')
    op.drop_column('delivery_services', 'deleted_by_user_id')
    op.drop_column('delivery_services', 'deleted_at')
    op.drop_column('delivery_services', 'is_deleted')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'deleted_by_user_id')
    op.drop_column('customers', 'deleted_at')
    op.drop_column('customers', 'is_deleted')
    op.alter_column('activities', 'workspace_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('activities', 'ip_address')
    op.drop_column('activities', 'metadata_json')
    op.drop_column('activities', 'actor_email')
    # ### end Alembic commands ###
